---
# Copyright (c) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

  - name: Create Scheduler key and CA certificate
    become: no
    connection: local
    command: >
      {{ gopath }}/bin/ciao-cert -anchor -role scheduler
      -email={{ ciao_admin_email }} -organization="{{ ciao_cert_organization }}"
      -ip={{ ciao_controller_ip }} -host={{ ciao_controller_fqdn }} -verify
    args:
      chdir: "{{ workdir }}"
      creates: CAcert-{{ ciao_controller_fqdn }}.pem

  - name: Create agent keys
    become: no
    connection: local
    command: >
      {{ gopath }}/bin/ciao-cert -role {{ item.role }} --anchor-cert
      cert-Scheduler-{{ ciao_controller_fqdn }}.pem -email={{ ciao_admin_email }}
      --organization="{{ ciao_cert_organization }}" -host=localhost -verify
    args:
      chdir: "{{ workdir }}"
      creates: "{{ item.creates }}"
    with_items:
      - role: agent
        creates: cert-CNAgent-localhost.pem
      - role: netagent
        creates: cert-NetworkingAgent-localhost.pem
      - role: cnciagent
        creates: cert-CNCIAgent-localhost.pem
      - role: controller
        creates: cert-Controller-localhost.pem
      - role: agent,netagent
        creates: cert-CNAgent-NetworkingAgent-localhost.pem

  - name: Copy certificates
    copy: src={{ workdir }}/{{ item }} dest=/etc/pki/ciao/{{ item }} owner=ciao mode=400
    with_items:
      - CAcert-{{ ciao_controller_fqdn }}.pem
      - cert-Controller-localhost.pem
      - cert-Scheduler-{{ ciao_controller_fqdn }}.pem
      - keystone_cert.pem
      - keystone_key.pem

  - name: Install keystone certificate
    copy:
      src: "{{ workdir }}/keystone_cert.pem"
      dest: "{{ keystone_cert }}"

  - name: Update CA certificates
    command: "{{ cacert_prog }}"
    args:
      creates: "{{ cacert_creates }}"
